name: DrowsyManagementTool
version: 1.0
main: com.stuart.javarealmtool.JavaRealmTool
api-version: 1.21
commands:
  rmt:
    description: Main management command
    permission: rmt.admin
    usage: /rmt
  ticket:
    description: Submit a ticket
    usage: /ticket new <message>
permissions:
  rmt.admin:
    description: Allows use of admin tools
    default: op