name: DrowsyManagementTool
version: 6.0
main: com.stuart.javarealmtool.JavaRealmTool
api-version: 1.21
commands:
  dmt:
    description: Main management command
    permission: dmt.admin
    usage: /dmt help
  ticket:
    description: Submit a ticket
    usage: /ticket new <message>
  tpa:
    description: Teleport request system
    usage: /tpa accept|deny <player>
  kit:
    description: Browse and claim kits
    usage: /kit
permissions:
  dmt.admin:
    description: Allows use of admin tools
    default: op